# Generated by Django 4.0 on 2022-05-19 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MisingPerson',
            new_name='MissingPerson',
        ),
        migrations.AlterModelOptions(
            name='missingperson',
            options={'ordering': ('first_name',), 'verbose_name': 'Mising People', 'verbose_name_plural': 'Missing People'},
        ),
    ]
