# Generated by Django 4.0 on 2022-05-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_rename_misingperson_missingperson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='contact_person',
            field=models.CharField(max_length=200, verbose_name='Contact Person'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='contact_relationship',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Husband', 'Husband'), ('Wife', 'Wife'), ('Guardian', 'Guardian'), ('Relative', 'Relative'), ('Friend', 'Friend'), ('Other', 'Other')], max_length=200, verbose_name='Relationship with Missing Person'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='Given Name'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=200, verbose_name='Gender of Missing Person'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='last_seen',
            field=models.CharField(max_length=200, verbose_name='Last Seen Location'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Leads', 'Leads'), ('Found', 'Found'), ('Closed', 'Closed')], max_length=200, verbose_name='Current Status'),
        ),
    ]
