# Generated by Django 4.0 on 2022-05-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_alter_missingperson_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='face_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Face ID of Missing Person'),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Person Background Check Done?'),
        ),
    ]
