# Generated by Django 4.0 on 2022-05-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_missingperson_face_id_missingperson_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.CharField(max_length=200, verbose_name='Last Seen Location')),
                ('description', models.TextField(max_length=1000, verbose_name='Any Other Important Details')),
                ('photo', models.ImageField(upload_to='reportedpersons/', verbose_name='Upload Photo of Reported Person')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is this valid reporting?')),
                ('face_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Face ID of Reported Person')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reported People',
                'verbose_name_plural': 'Reported People',
                'ordering': ('created_date',),
            },
        ),
    ]
