# Generated by Django 4.0 on 2022-05-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_reportedperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedperson',
            name='is_matched_with_missing_person',
            field=models.BooleanField(default=False, verbose_name='Has the match found?'),
        ),
        migrations.AddField(
            model_name='reportedperson',
            name='matched_confindence',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Details of Match'),
        ),
    ]
