# Generated by Django 4.0 on 2022-05-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_reportedperson_is_matched_with_missing_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedperson',
            name='matched_face_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Face ID of Matched Person'),
        ),
    ]
