# Generated by Django 4.0.4 on 2022-05-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_alter_missingperson_phone'),
        ('people', '0007_reportedperson_matched_face_id'),
    ]

    operations = [
    ]
