# Generated by Django 4.0.4 on 2022-05-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_alter_missingperson_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedperson',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Any Other Important Details'),
        ),
        migrations.AlterField(
            model_name='reportedperson',
            name='last_seen',
            field=models.CharField(max_length=200, verbose_name='Found Location'),
        ),
    ]
