# Generated by Django 4.0.4 on 2022-05-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_alter_reportedperson_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact Email ID'),
        ),
    ]
