# Generated by Django 4.0.4 on 2022-05-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_missingperson_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='contact_email',
            field=models.EmailField(max_length=254, verbose_name='Contact Email ID'),
        ),
    ]
