# Generated by Django 4.0.4 on 2022-05-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_alter_missingperson_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='found_location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Found Location'),
        ),
    ]
