# Generated by Django 4.0.4 on 2022-05-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_missingperson_found_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='is_contacted',
            field=models.BooleanField(default=False, verbose_name='Contact person has been informed?'),
        ),
    ]
